language: bash

env:
  - TOOL=python
  - TOOL=awscli
  - TOOL=ansible
  - TOOL=kitchen
  - TOOL=k8s

services:
  - docker

before_install:
  - cd $TOOL

before_script:
  - docker run --rm -i hadolint/hadolint < Dockerfile

script:
  - time bash build.sh || docker build -t ${DOCKER_USERNAME}/${TOOL}:latest .
  - time bash test.sh || true

before_deploy:
  - cd ..

deploy:
  provider: script
  script: bash release.sh
  on:
    branch: master
