# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "ffi", "~> 1.10.0"

gem "test-kitchen", "~> 1.24"

gem "kitchen-docker", "~> 2.9"

gem "kitchen-ansible", "~> 0.49.1"

gem "kitchen-inspec", "~> 1.0.1"

